apiVersion: v1
kind: Service
metadata:
  name: seat-reservation-app
  namespace: event-seat
spec:
  selector:
    app: seat-reservation-app
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
